#cloud-config
hostname: apache2
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIImhf7JdFUojxgrd5H3Tum8nu3qHbaM02XKy0Boa3JZu arooca27@gmail.com
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text