---
- name: Descargar WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extraer WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Crear directorio
  file:
    path: /var/www/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copiar archivos
  shell: cp -r /tmp/wordpress/* /var/www/wordpress/
  args:
    creates: /var/www/wordpress/index.php

- name: Permisos
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    recurse: yes

- name: Configurar wp-config
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
    mode: '0640'

- name: Limpiar
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/wordpress.tar.gz
    - /tmp/wordpress
