---
- name: Actualizar sistema
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: AÃ±adir entradas al /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - "10.0.0.2 mariadb"
    - "10.0.1.10 server1"
    - "10.0.1.11 server2"
