---
- name: Configurar servidor de base de datos
  hosts: mariadb
  roles:
    - mariadb

- name: Configurar servidor PHP-FPM
  hosts: php-fpm
  roles:
    - php-fpm

- name: Configurar servidor web (Nginx + WordPress)
  hosts: nginx
  vars:
    db_host: "192.168.200.252"  # IP del servidor MariaDB
  roles:
    - nginx
    - wordpress
