---
- name: Detener y deshabilitar Apache2 si existe
  systemd:
    name: apache2
    state: stopped
    enabled: no
  failed_when: false
  ignore_errors: yes

- name: Instalar Nginx
  apt:
    name: nginx
    state: present

- name: Eliminar default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Crear virtualhosts
  template:
    src: vhost.j2
    dest: "/etc/nginx/sites-available/{{ item.name }}.conf"
  loop: "{{ virtualhosts }}"
  notify: reload nginx

- name: Habilitar virtualhosts
  file:
    src: "/etc/nginx/sites-available/{{ item.name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
    state: link
  loop: "{{ virtualhosts }}"
  notify: reload nginx

- name: Iniciar Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
